SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID IN (
    SELECT C.MEMBER_ID
    FROM REST_REVIEW C
    GROUP BY C.MEMBER_ID
    HAVING COUNT(C.REVIEW_ID) = (
        SELECT MAX(TMP.CNT)
        FROM (
            SELECT D.MEMBER_ID, COUNT(D.REVIEW_ID) AS CNT
            FROM REST_REVIEW D
            GROUP BY D.MEMBER_ID
        ) TMP
    )
)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT
