SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', C.FILE_ID, C.FILE_NAME, C.FILE_EXT) AS FILE_PATH
FROM (
    SELECT A.*
    FROM USED_GOODS_BOARD A
    ORDER BY A.VIEWS DESC
    LIMIT 1
) B
LEFT JOIN USED_GOODS_FILE C ON B.BOARD_ID = C.BOARD_ID
ORDER BY C.FILE_ID DESC;